"""create all tables

Revision ID: 469572dc2184
Revises: 
Create Date: 2026-08-23 21:54:48.629841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469572dc2184'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'client_vehicle_interests', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'client_vehicle_interests', type_='foreignkey')
    # ### end Alembic commands ###
