"""add boleto_generado to sales

Revision ID: 77a8207ba0b9
Revises: ec5bfeec6999
Create Date: 2026-09-21 18:40:06.655971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a8207ba0b9'
down_revision: Union[str, Sequence[str], None] = 'ec5bfeec6999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('boleto_generado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'boleto_generado')
    # ### end Alembic commands ###
