"""add price_internal to vehicles

Revision ID: 91cd203a741c
Revises: cbf221a90090
Create Date: 2026-09-24 11:17:58.943675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cd203a741c'
down_revision: Union[str, Sequence[str], None] = 'cbf221a90090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('price_internal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'price_internal')
    # ### end Alembic commands ###
