"""add price_cash to vehicles

Revision ID: bd48a7458a16
Revises: f4f62f5375f2
Create Date: 2026-09-21 15:00:41.193990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd48a7458a16'
down_revision: Union[str, Sequence[str], None] = 'f4f62f5375f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('price_cash', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'price_cash')
    # ### end Alembic commands ###
