"""add sale details, company settings, and vehicle/client complementary fields

Revision ID: ec5bfeec6999
Revises: bd48a7458a16
Create Date: 2026-09-21 17:25:31.196909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5bfeec6999'
down_revision: Union[str, Sequence[str], None] = 'bd48a7458a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    op.add_column('clients', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('locality', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('document_number', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('reserva_amount', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('entrega_amount', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('otros_amount', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('saldo_financiado', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('cantidad_cuotas', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('monto_cuota', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('fecha_primera_cuota', sa.DateTime(), nullable=True))
    op.add_column('sales', sa.Column('observaciones', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('engine_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('chassis_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'chassis_number')
    op.drop_column('vehicles', 'engine_number')
    op.drop_column('sales', 'observaciones')
    op.drop_column('sales', 'fecha_primera_cuota')
    op.drop_column('sales', 'monto_cuota')
    op.drop_column('sales', 'cantidad_cuotas')
    op.drop_column('sales', 'saldo_financiado')
    op.drop_column('sales', 'otros_amount')
    op.drop_column('sales', 'entrega_amount')
    op.drop_column('sales', 'reserva_amount')
    op.drop_column('clients', 'document_number')
    op.drop_column('clients', 'locality')
    op.drop_column('clients', 'address')
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
