"""add is_active to vehicles and clients

Revision ID: f4b0596c8619
Revises: 0333d2d77020
Create Date: 2026-08-23 23:19:03.074951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b0596c8619'
down_revision: Union[str, Sequence[str], None] = '0333d2d77020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_active')
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
