"""add is_offer to vehicles

Revision ID: f4f62f5375f2
Revises: f4b0596c8619
Create Date: 2026-09-13 15:40:52.315697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f62f5375f2'
down_revision: Union[str, Sequence[str], None] = 'f4b0596c8619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('is_offer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_offer')
    # ### end Alembic commands ###
